// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParsingProjectMVC.Services;

#nullable disable

namespace ParsingProjectMVC.Migrations
{
    [DbContext(typeof(ParsingDbContext))]
    [Migration("20240712133918_IsimDegisiklikleri")]
    partial class IsimDegisiklikleri
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParsingProjectMVC.Models.KuyuGrubuModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("KuyuGrubuAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SahaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SahaId");

                    b.ToTable("KuyuGrubu");
                });

            modelBuilder.Entity("ParsingProjectMVC.Models.KuyuModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Boylam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Enlem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KuyuAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KuyuGrubuId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KuyuGrubuId");

                    b.ToTable("Kuyu");
                });

            modelBuilder.Entity("ParsingProjectMVC.Models.SahaModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SahaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Saha");
                });

            modelBuilder.Entity("ParsingProjectMVC.Models.WellboreModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Derinlik")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KuyuId")
                        .HasColumnType("int");

                    b.Property<string>("WellboreAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KuyuId");

                    b.ToTable("Wellbore");
                });

            modelBuilder.Entity("ParsingProjectMVC.Models.KuyuGrubuModel", b =>
                {
                    b.HasOne("ParsingProjectMVC.Models.SahaModel", "Saha")
                        .WithMany()
                        .HasForeignKey("SahaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Saha");
                });

            modelBuilder.Entity("ParsingProjectMVC.Models.KuyuModel", b =>
                {
                    b.HasOne("ParsingProjectMVC.Models.KuyuGrubuModel", "KuyuGrubu")
                        .WithMany()
                        .HasForeignKey("KuyuGrubuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KuyuGrubu");
                });

            modelBuilder.Entity("ParsingProjectMVC.Models.WellboreModel", b =>
                {
                    b.HasOne("ParsingProjectMVC.Models.KuyuModel", "Kuyu")
                        .WithMany()
                        .HasForeignKey("KuyuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kuyu");
                });
#pragma warning restore 612, 618
        }
    }
}
